# Generated by Django 5.2.2 on 2025-06-08 13:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date_recorded',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='electricity_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='rent_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='water_gallons',
        ),
        migrations.AddField(
            model_name='payment',
            name='electricity_bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='water_bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
