# Generated by Django 5.2.2 on 2025-06-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_payment_date_recorded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='emergency_contact',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_number',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_type',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
