# Generated by Django 5.2.2 on 2025-06-12 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_tenant_address_tenant_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_ids/'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='emergency_contact',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[\\d\\s\\-]{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id_type',
            field=models.CharField(choices=[('National ID', 'National ID'), ('Driver’s License', 'Driver’s License'), ('Passport', 'Passport'), ('Voter’s ID', 'Voter’s ID'), ('Student ID', 'Student ID'), ('Other', 'Other')], max_length=50),
        ),
    ]
