# Generated by Django 5.2.2 on 2025-06-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_tenant_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='electricity_bill',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='water_bill',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
