# Generated by Django 5.2.2 on 2025-06-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_payment_electricity_bill_alter_payment_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historylog',
            name='action',
            field=models.CharField(choices=[('ADD', 'Added Tenant'), ('REMOVE', 'Removed Tenant'), ('UPDATE', 'Updated Info'), ('PAYMENT', 'Payment Recorded')], max_length=100),
        ),
    ]
